# config_1024mb_reed_solomon_rs28.yaml
# FLUTE 1024MB文件传输专用配置 (reed_soloon_rs28)
# Rate under: unlimited Mbits/sec
sender:
  network:
    # destination: "192.168.100.2:3500" # "192.168.1.102:3500"  # win11-IP
    # bind_address: "192.168.100.1" # "192.168.1.103" # linux-IP
    destination: "192.168.100.2:3500"  # receiver IP
    bind_address: "192.168.100.1" # sender IP
    bind_port: 0
    send_interval_micros: 0

  fec:
    type: "reed_solomon_gf28"
    encoding_symbol_length: 1400
    max_number_of_parity_symbols: 4
    maximum_source_block_length: 60
    symbol_alignment: 8
    sub_blocks_length: 1

  flute:
    tsi: 1
    interleave_blocks: 4     # 更高块交错

  logging:
    progress_interval: 100  # 更少日志

  files:
    - path: "../../../test_files/test_1mb.bin"
      content_type: "application/octet-stream"
      priority: 0
      version: 1

  # 新增速率控制参数
  max_rate_kbps: 0 # 9000
  send_interval_micros: 0

receiver:
  network:
    bind_address: "192.168.100.2"  # veth-receiver IP
    port: 3500

  storage:
    destination_dir: "../../../flute_recv"
    enable_md5_check: true

  logging:
    progress_interval: 100

  advanced:
    buffer_size: 8388608     # 4MB缓冲区
    cleanup_interval: 2000   # 减少清理频率
    log_interval: 500       # 减少日志频率
    max_memory_mb: 8192      # 8GB内存限制

