# config_1mb_no_code.yaml
# FLUTE 1MB文件传输专用配置
sender:
  network:
    destination: "192.168.100.2:3500"  # receiver IP
    bind_address: "192.168.100.1" # sender IP
    bind_port: 0
    send_interval_micros: 80

  fec:
    type: "no_code"
    encoding_symbol_length: 1400
    max_number_of_parity_symbols: 0
    maximum_source_block_length: 60
    symbol_alignment: 1
    sub_blocks_length: 1

  flute:
    tsi: 1
    interleave_blocks: 4

  logging:
    progress_interval: 500

  files:
    - path: "../../../test_files/test_1mb.bin"
      content_type: "application/octet-stream"
      priority: 0
      version: 1

receiver:
  network:
    bind_address: "192.168.100.2"  # receiver IP
    port: 3500

  storage:
    # destination_dir: "C:\\Users\\Administrator\\Desktop\\flute\\flute_recv"
    destination_dir: "../../../flute_recv"
    enable_md5_check: true

  logging:
    progress_interval: 10

  advanced:
    buffer_size: 1048576     # 1MB缓冲区，避免高流量丢包
    cleanup_interval: 100    # 每100个包清理一次
    log_interval: 50         # 每50个包记录日志
    max_memory_mb: 256       # 最大内存256MB

