# config_1024mb_raptorq.yaml
# FLUTE 1024MB文件传输专用配置 (raptorq)
# Rate under: unlimited Mbits/sec
sender:
  network:
    destination: "192.168.1.102:3500"  # win11-IP
    bind_address: "192.168.1.103" # linux-IP
    bind_port: 0
    send_interval_micros: 1  

  fec:
    type: "raptorq"
    encoding_symbol_length: 38912
    max_number_of_parity_symbols: 100
    maximum_source_block_length: 120
    symbol_alignment: 8
    sub_blocks_length: 1

  flute:
    tsi: 1
    interleave_blocks: 4     # 更高块交错

  logging:
    progress_interval: 100  # 更少日志

  files:
    - path: "/home/Halllo/Projects/flute/examples/flute-sender/src/files_send/test_1024mb.bin"
      content_type: "application/octet-stream"
      priority: 0
      version: 1
      
  # 新增速率控制参数
  max_rate_kbps: 0  
  send_interval_micros: 1  

receiver:
  network:
    bind_address: "192.168.1.102"  # win11-IP
    port: 3500

  storage:
    destination_dir: "C:\\Users\\Administrator\\Desktop\\flute\\flute_recv"
    enable_md5_check: true

  logging:
    progress_interval: 100

  advanced:
    buffer_size: 8388608     # 4MB缓冲区
    cleanup_interval: 2000   # 减少清理频率
    log_interval: 500       # 减少日志频率
    max_memory_mb: 8192      # 8GB内存限制

