# config_1024mb_batch_no_code.yaml
# FLUTE 1024MB文件传输专用配置 (no_code)
sender:
  network:
    destination: "127.0.0.1:3500"
    bind_address: "0.0.0.0"
    bind_port: 0
    send_interval_micros: 2  # 稍微降低发送速度

  fec:
    type: "no_code"
    symbol_size: 16384       # 改为16KB符号大小
    source_symbols: 6400     # 100MB/16KB ≈ 6400
    repair_symbols: 0
    encoding_symbol_id_length: 4
    maximum_source_block_length: 256

  flute:
    tsi: 1
    interleave_blocks: 16     # 更高块交错

  logging:
    progress_interval: 2000  # 更少日志

  files:
    - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1024mb_random_1.bin"
      content_type: "application/octet-stream"
      priority: 0
      version: 1
    - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1024mb_random_2.bin"
      content_type: "application/octet-stream"
      priority: 0
      version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_3.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_4.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_5.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_6.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_7.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_8.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_9.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1
    # - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1gb_10.bin"
    #   content_type: "application/octet-stream"
    #   priority: 0
    #   version: 1

receiver:
  network:
    bind_address: "0.0.0.0"
    port: 3500

  storage:
    destination_dir: "/home/halllo/flute-main/examples/flute-receiver/src/files_save"
    enable_md5_check: false

  logging:
    progress_interval: 500

  advanced:
    buffer_size: 1048576     # 增大到1MB缓冲区
    cleanup_interval: 2000   # 减少清理频率
    log_interval: 500       # 减少日志频率
    max_memory_mb: 2048      # 增大到2GB内存限制
    max_retries: 5           # 新增：最大重试次数
    retry_delay_ms: 200      # 新增：重试延迟200ms