# config_1024mb_raptorq.yaml
# FLUTE 1024MB文件传输专用配置 (raptorq)
# Rate under: unlimited Mbits/sec
sender:
  network:
    destination: "192.168.100.2:3500"  # receiver IP
    bind_address: "192.168.100.1" # sender IP
    bind_port: 0
    send_interval_micros: 1  

  fec:
    type: "raptorq"
    encoding_symbol_length: 16384     # 1.4KB符号，UDP兼容
    max_number_of_parity_symbols: 10  # 减少冗余符号，提高速度  
    maximum_source_block_length: 50  # 优化为支持大文件传输 (充分利用48位传输能力)
    symbol_alignment: 4
    sub_blocks_length: 1

  flute:
    tsi: 1
    interleave_blocks: 4     # 更高块交错

  logging:
    progress_interval: 100  # 更少日志

  files:
    - path: "../../../test_files/test_1024mb.bin"
      content_type: "application/octet-stream"
      priority: 0
      version: 1
      
  # 新增速率控制参数
  max_rate_kbps: 0  
  send_interval_micros: 1  

receiver:
  network:
    bind_address: "192.168.100.2"  # veth-receiver IP
    port: 3500

  storage:
    destination_dir: "../../../flute_recv"
    enable_md5_check: true

  logging:
    progress_interval: 100

  advanced:
    buffer_size: 8388608     # 8MB缓冲区
    cleanup_interval: 2000   # 减少清理频率
    log_interval: 500       # 减少日志频率
    max_memory_mb: 8192      # 8GB内存限制

