# config_1024mb_no_code.yaml
# FLUTE 1024MB文件传输专用配置 (no_code)
# Rate under: unlimited Mbits/sec
sender:
  network:
    destination: "192.168.100.2:3500"  # 使用 veth-receiver 的 IP
    bind_address: "192.168.100.1"
    bind_port: 0
    send_interval_micros: 1  

  fec:
    type: "no_code"
    encoding_symbol_length: 16384
    max_number_of_parity_symbols: 100
    maximum_source_block_length: 120
    symbol_alignment: 8
    sub_blocks_length: 1

  flute:
    tsi: 1
    interleave_blocks: 16     # 更高块交错

  logging:
    progress_interval: 2000  # 更少日志

  files:
    - path: "/home/halllo/flute-main/examples/flute-sender/src/files_send/test_1024mb.bin"
      content_type: "application/octet-stream"
      priority: 0
      version: 1
      
  # 新增速率控制参数
  max_rate_kbps: 0  
  send_interval_micros: 1  

receiver:
  network:
    bind_address: "192.168.100.2"  # 绑定到 veth-receiver
    port: 3500

  storage:
    destination_dir: "/home/halllo/flute-main/examples/flute-receiver/src/files_save"
    enable_md5_check: true

  logging:
    progress_interval: 500

  advanced:
    buffer_size: 1048576     # 增大到1MB缓冲区
    cleanup_interval: 2000   # 减少清理频率
    log_interval: 500       # 减少日志频率
    max_memory_mb: 2048      # 增大到2GB内存限制
