# flute-sender/config/sender_config.yaml

# 网络配置
network:
  destination: "127.0.0.1:3500"    # 目标地址:端口
  bind_address: "0.0.0.0"           # 绑定地址
  bind_port: 0                      # 绑定端口(0=自动分配)
  send_buffer_size: 1048576         # 发送缓冲区大小(1MB)
  send_interval_micros: 10          # 发送间隔(微秒)

# FEC配置
fec:
  type: "no_code"            # no_code, reed_solomon, raptor, raptorq
  symbol_size: 32768                 # 符号大小(字节) (Default: 1400)
  source_symbols: 200                # 源符号数量 (Default:60)
  repair_symbols: 20                 # 修复符号数量 (Default:4)
  encoding_symbol_id_length: 2      # 编码符号ID长度 (Default:1)
  maximum_source_block_length: 10     # 最大源块长度 (Default:4)

# FLUTE发送器配置
flute:
  tsi: 1                            # 传输会话标识符
  content_type: "application/octet-stream"  # 默认内容类型
  enable_md5: true                  # 启用MD5校验
  version: 1                        # 文件版本号
  publish_mode: "FullFDT"           # 发布模式

# 传输控制
transfer:
  priority_queue: 0                 # 优先级队列
  interleave_blocks: 1              # 块交错数量
  target_duration_secs: 900          # 目标传输时长(秒)
  carousel_mode: "None"             # 轮播模式: None, Delay, Interval

# 日志配置
logging:
  level: "info"                     # 日志级别: error, warn, info, debug, trace
  show_progress: true               # 显示进度信息
  progress_interval: 100            # 进度显示间隔(包数)

# 要发送的文件列表
files:
  - path: "files_send/rfc5052.txt.pdf"
    content_type: "application/pdf"
    priority: 0
    version: 1
  # - path: "files_send/Mid/1J"
  #   content_type: "application/octet-stream"
  #   priority: 0
  #   version: 1
  # - path: "files_send/Mid/1K"
  #   content_type: "application/octet-stream"
  #   priority: 0
  #   version: 1
  # - path: "files_send/Mid/1O"
  #   content_type: "application/octet-stream"
  #   priority: 0
  #   version: 1
  # - path: "files_send/Mid/1S"
  #   content_type: "application/octet-stream"
  #   priority: 0
  #   version: 1
  # - path: "files_send/Mid/1Z"
  #   content_type: "application/octet-stream"
  #   priority: 0
  #   version: 1  

# 高级配置
advanced:
  cenc: "Null"                      # 内容编码: Null, Deflate, Zlib, Gzip
  use_complete_fdt: true            # 使用完整FDT
  allow_updates: true               # 允许更新
  max_packet_size: 16777216